debug:
  address: ":9091"
  system:
    token:
  mysql:
    demo:
      # user:password@/dbname
      address: "root:@/demo" 
  example:
    host: "baidu.com"

release:
  address: ":9091"
  system:
    token: 
  mysql:
    demo:
      # user:password@/dbname
      address: "root:@/demo" 
  example:
    host: "baidu.com"


