debug:
  address: ":9091"
  system:
    token:
  mysql:
    # user:password@/dbname
    address: "root:@/mydbname" 
  example:
    host: "baidu.com"

release:
  address: ":9091"
  system:
    token: 
  mysql:
    # user:password@/dbname
    address: "root:@/mydbname"
  example:
    host: "baidu.com"


